# `panic`

Самый простой рычаг обработки ошибок, с которым мы познакомимся – это `panic`.
Он выводит сообщение с ошибкой, начинает процедуру
раскрутки обоймы и, чаще всего, завершает программу. В данном примере мы явно вызываем `panic` в случае ошибки:

```rust,editable,ignore,mdbook-runnable
fn give_princess(gift: &str) {
    // Принцесса ненавидит змей, поэтому нам нужно остановиться, если она не одобрит!
    if gift == "змея" { panic!("AAAaaaaa!!!!"); }

    println!("Я люблю тебя, {}!!!!!", gift);
}

fn main() {
    give_princess("плюшевый мишка");
    give_princess("змея");
}
```
